// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJKdTvTurB5Xm9twog27NcF-IJJidgu6Y',
    appId: '1:678664219518:web:35108368c5f9085f5d212f',
    messagingSenderId: '678664219518',
    projectId: 'bibaho-sheba-c7874',
    authDomain: 'bibaho-sheba-c7874.firebaseapp.com',
    storageBucket: 'bibaho-sheba-c7874.firebasestorage.app',
    measurementId: 'G-5ETGN5M82F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHgH2kbS1x3XFedEhZpvlUvmuWish_slw',
    appId: '1:678664219518:android:529a1f6e8f3bf1285d212f',
    messagingSenderId: '678664219518',
    projectId: 'bibaho-sheba-c7874',
    storageBucket: 'bibaho-sheba-c7874.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOprEf4y084YKhZbr7r1KCV7swirfxOjc',
    appId: '1:678664219518:ios:440d581b23dded835d212f',
    messagingSenderId: '678664219518',
    projectId: 'bibaho-sheba-c7874',
    storageBucket: 'bibaho-sheba-c7874.firebasestorage.app',
    iosBundleId: 'com.example.bibahoSheba',
  );
}
